export const theme = {
    colors: {
        background: '#0A0A0A',
        backgroundGradient: ['#0A0A0A', '#1A1A1A'],
        surface: '#1C1C1E',
        surfaceElevated: '#2C2C2E',
        primary: '#FF6B4A',
        primaryDark: '#E85537',
        primaryLight: '#FF8C6F',
        secondary: '#FFB84D',
        accent: '#4DFFBD',
        text: '#FFFFFF',
        textSecondary: '#A0A0A0',
        textTertiary: '#666666',
        border: '#2C2C2E',
        borderLight: '#3C3C3E',
        error: '#FF5252',
        success: '#4DFFBD',
        warning: '#FFB84D',
        card: '#1C1C1E',
        cardHover: '#252527',
        overlay: 'rgba(0, 0, 0, 0.7)',
    },
    gradients: {
        primary: ['#FF6B4A', '#FF8C6F'],
        secondary: ['#FFB84D', '#FFD480'],
        dark: ['#0A0A0A', '#1A1A1A'],
        card: ['#1C1C1E', '#252527'],
    },
    shadows: {
        small: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 4,
            elevation: 2,
        },
        medium: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.25,
            shadowRadius: 8,
            elevation: 4,
        },
        large: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.35,
            shadowRadius: 16,
            elevation: 8,
        },
    },
    spacing: {
        xs: 4,
        s: 8,
        m: 16,
        l: 24,
        xl: 32,
        xxl: 48,
    },
    borderRadius: {
        xs: 4,
        s: 8,
        m: 12,
        l: 16,
        xl: 24,
        round: 999,
    },
    typography: {
        h1: { fontSize: 32, fontWeight: 'bold', color: '#FFFFFF', lineHeight: 40 },
        h2: { fontSize: 26, fontWeight: 'bold', color: '#FFFFFF', lineHeight: 34 },
        h3: { fontSize: 22, fontWeight: '600', color: '#FFFFFF', lineHeight: 28 },
        h4: { fontSize: 18, fontWeight: '600', color: '#FFFFFF', lineHeight: 24 },
        body: { fontSize: 16, color: '#FFFFFF', lineHeight: 24 },
        bodyMedium: { fontSize: 16, fontWeight: '500', color: '#FFFFFF', lineHeight: 24 },
        bodyBold: { fontSize: 16, fontWeight: 'bold', color: '#FFFFFF', lineHeight: 24 },
        caption: { fontSize: 14, color: '#A0A0A0', lineHeight: 20 },
        small: { fontSize: 12, color: '#666666', lineHeight: 16 },
    },
};
